# Generated by Django 4.2.11 on 2024-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_category_name_az_category_name_en_category_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
