# Generated by Django 4.2.11 on 2024-10-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
